// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/microservice-template/service.proto

package microservice_template

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Error struct {
	Code                 int32                       `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string                      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details              *any.Any                    `protobuf:"bytes,4,opt,name=details,proto3" json:"details,omitempty"`
	Validation           map[string]*ValidationError `protobuf:"bytes,5,rep,name=validation,proto3" json:"validation,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_382efac743cc81e6, []int{0}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Error) GetDetails() *any.Any {
	if m != nil {
		return m.Details
	}
	return nil
}

func (m *Error) GetValidation() map[string]*ValidationError {
	if m != nil {
		return m.Validation
	}
	return nil
}

type ValidationError struct {
	Errors               []string `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidationError) Reset()         { *m = ValidationError{} }
func (m *ValidationError) String() string { return proto.CompactTextString(m) }
func (*ValidationError) ProtoMessage()    {}
func (*ValidationError) Descriptor() ([]byte, []int) {
	return fileDescriptor_382efac743cc81e6, []int{1}
}

func (m *ValidationError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidationError.Unmarshal(m, b)
}
func (m *ValidationError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidationError.Marshal(b, m, deterministic)
}
func (m *ValidationError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidationError.Merge(m, src)
}
func (m *ValidationError) XXX_Size() int {
	return xxx_messageInfo_ValidationError.Size(m)
}
func (m *ValidationError) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidationError.DiscardUnknown(m)
}

var xxx_messageInfo_ValidationError proto.InternalMessageInfo

func (m *ValidationError) GetErrors() []string {
	if m != nil {
		return m.Errors
	}
	return nil
}

type Req struct {
	Str                  string   `protobuf:"bytes,1,opt,name=str,proto3" json:"str,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Req) Reset()         { *m = Req{} }
func (m *Req) String() string { return proto.CompactTextString(m) }
func (*Req) ProtoMessage()    {}
func (*Req) Descriptor() ([]byte, []int) {
	return fileDescriptor_382efac743cc81e6, []int{2}
}

func (m *Req) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Req.Unmarshal(m, b)
}
func (m *Req) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Req.Marshal(b, m, deterministic)
}
func (m *Req) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Req.Merge(m, src)
}
func (m *Req) XXX_Size() int {
	return xxx_messageInfo_Req.Size(m)
}
func (m *Req) XXX_DiscardUnknown() {
	xxx_messageInfo_Req.DiscardUnknown(m)
}

var xxx_messageInfo_Req proto.InternalMessageInfo

func (m *Req) GetStr() string {
	if m != nil {
		return m.Str
	}
	return ""
}

type Resp struct {
	Str                  string   `protobuf:"bytes,1,opt,name=str,proto3" json:"str,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Resp) Reset()         { *m = Resp{} }
func (m *Resp) String() string { return proto.CompactTextString(m) }
func (*Resp) ProtoMessage()    {}
func (*Resp) Descriptor() ([]byte, []int) {
	return fileDescriptor_382efac743cc81e6, []int{3}
}

func (m *Resp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resp.Unmarshal(m, b)
}
func (m *Resp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resp.Marshal(b, m, deterministic)
}
func (m *Resp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resp.Merge(m, src)
}
func (m *Resp) XXX_Size() int {
	return xxx_messageInfo_Resp.Size(m)
}
func (m *Resp) XXX_DiscardUnknown() {
	xxx_messageInfo_Resp.DiscardUnknown(m)
}

var xxx_messageInfo_Resp proto.InternalMessageInfo

func (m *Resp) GetStr() string {
	if m != nil {
		return m.Str
	}
	return ""
}

func (m *Resp) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*Error)(nil), "microservice_template.Error")
	proto.RegisterMapType((map[string]*ValidationError)(nil), "microservice_template.Error.ValidationEntry")
	proto.RegisterType((*ValidationError)(nil), "microservice_template.ValidationError")
	proto.RegisterType((*Req)(nil), "microservice_template.Req")
	proto.RegisterType((*Resp)(nil), "microservice_template.Resp")
}

func init() {
	proto.RegisterFile("proto/microservice-template/service.proto", fileDescriptor_382efac743cc81e6)
}

var fileDescriptor_382efac743cc81e6 = []byte{
	// 333 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xcd, 0x4a, 0xf3, 0x40,
	0x14, 0x86, 0xbf, 0x34, 0x49, 0x4b, 0x4f, 0x17, 0x9f, 0x0c, 0xfe, 0xc4, 0xe8, 0x22, 0x64, 0x21,
	0x29, 0xe8, 0x04, 0xe2, 0x46, 0xc4, 0x4d, 0x91, 0xee, 0xba, 0x1a, 0xc1, 0xad, 0x4c, 0xdb, 0x63,
	0x09, 0x4e, 0x33, 0xe9, 0xcc, 0xb4, 0x90, 0x5b, 0xf1, 0x6a, 0x25, 0x93, 0x46, 0xea, 0x4f, 0xdc,
	0x9d, 0xc9, 0x79, 0xde, 0xbc, 0x0f, 0x33, 0x30, 0x2e, 0x95, 0x34, 0x32, 0x5d, 0xe7, 0x0b, 0x25,
	0x35, 0xaa, 0x5d, 0xbe, 0xc0, 0x1b, 0x83, 0xeb, 0x52, 0x70, 0x83, 0xe9, 0xfe, 0x03, 0xb5, 0x0c,
	0x39, 0x39, 0x84, 0x5e, 0x5a, 0x28, 0x3c, 0x5f, 0x49, 0xb9, 0x12, 0x98, 0x5a, 0x68, 0xbe, 0x7d,
	0x4d, 0x79, 0x51, 0x35, 0x89, 0xf8, 0xbd, 0x07, 0xfe, 0x54, 0x29, 0xa9, 0x08, 0x01, 0x6f, 0x21,
	0x97, 0x18, 0x38, 0x91, 0x93, 0xf8, 0xcc, 0xce, 0x24, 0x80, 0xc1, 0x1a, 0xb5, 0xe6, 0x2b, 0x0c,
	0x7a, 0x91, 0x93, 0x0c, 0x59, 0x7b, 0x24, 0x14, 0x06, 0x4b, 0x34, 0x3c, 0x17, 0x3a, 0xf0, 0x22,
	0x27, 0x19, 0x65, 0xc7, 0xb4, 0x29, 0xa1, 0x6d, 0x09, 0x9d, 0x14, 0x15, 0x6b, 0x21, 0x32, 0x03,
	0xd8, 0x71, 0x91, 0x2f, 0xb9, 0xc9, 0x65, 0x11, 0xf8, 0x91, 0x9b, 0x8c, 0xb2, 0x6b, 0xfa, 0xab,
	0x2e, 0xb5, 0x3e, 0xf4, 0xf9, 0x13, 0x9f, 0x16, 0x46, 0x55, 0xec, 0x20, 0x1f, 0x22, 0xfc, 0xff,
	0xb6, 0x26, 0x47, 0xe0, 0xbe, 0x61, 0x65, 0xed, 0x87, 0xac, 0x1e, 0xc9, 0x03, 0xf8, 0x3b, 0x2e,
	0xb6, 0x8d, 0xfa, 0x28, 0xbb, 0xea, 0x68, 0x3b, 0xf8, 0x51, 0xdd, 0xcb, 0x9a, 0xd0, 0x7d, 0xef,
	0xce, 0x89, 0xc7, 0x5f, 0x6a, 0xec, 0x2d, 0x9d, 0x42, 0x1f, 0xeb, 0x41, 0x07, 0x4e, 0xe4, 0x26,
	0x43, 0xb6, 0x3f, 0xc5, 0x67, 0xe0, 0x32, 0xdc, 0xd4, 0x16, 0xda, 0xa8, 0xd6, 0x42, 0x1b, 0x15,
	0xcf, 0xc0, 0x63, 0xa8, 0xcb, 0x9f, 0x1b, 0x92, 0x81, 0x6f, 0xc3, 0x7b, 0xbf, 0xcb, 0xbf, 0x6e,
	0x83, 0x35, 0x68, 0x36, 0x83, 0xc1, 0x53, 0x03, 0x90, 0x09, 0x78, 0x8f, 0x5c, 0x08, 0x12, 0x76,
	0xe4, 0x18, 0x6e, 0xc2, 0x8b, 0xce, 0x9d, 0x2e, 0xe3, 0x7f, 0xf3, 0xbe, 0x7d, 0xab, 0xdb, 0x8f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xcb, 0x26, 0x90, 0xb7, 0x62, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServiceClient interface {
	Call(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error)
}

type serviceClient struct {
	cc *grpc.ClientConn
}

func NewServiceClient(cc *grpc.ClientConn) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) Call(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error) {
	out := new(Resp)
	err := c.cc.Invoke(ctx, "/microservice_template.Service/Call", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceServer is the server API for Service service.
type ServiceServer interface {
	Call(context.Context, *Req) (*Resp, error)
}

// UnimplementedServiceServer can be embedded to have forward compatible implementations.
type UnimplementedServiceServer struct {
}

func (*UnimplementedServiceServer) Call(ctx context.Context, req *Req) (*Resp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Call not implemented")
}

func RegisterServiceServer(s *grpc.Server, srv ServiceServer) {
	s.RegisterService(&_Service_serviceDesc, srv)
}

func _Service_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/microservice_template.Service/Call",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).Call(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

var _Service_serviceDesc = grpc.ServiceDesc{
	ServiceName: "microservice_template.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Call",
			Handler:    _Service_Call_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/microservice-template/service.proto",
}
