apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: microservice-template
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-template
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      creationTimestamp: null
      labels:
        app: microservice-template
    spec:
      containers:
        - name: microservice-template
          image: microservice-template:latest
          imagePullPolicy: IfNotPresent
          args:
            - -grpc
            - -twirp
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 8888
              name: grpc
          # resources:
          #   requests:
          #     cpu: 500m
