apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: microservice-template
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-template
  strategy: {}
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      creationTimestamp: null
      labels:
        app: microservice-template
    spec:
      containers:
        - env:
            - name: GRPC_PORT
              value: "8080"
          image: microservice-template:latest
          imagePullPolicy: IfNotPresent
          name: microservice-template
          ports:
            - containerPort: 8080
              name: grpc
            - containerPort: 8888
              name: http
          # resources:
          #   requests:
          #     cpu: 500m
      serviceAccountName: microservice-template
status: {}
