apiVersion: v1
kind: Service
metadata:
  name: lb-microservice-template
spec:
  type: LoadBalancer
  selector:
    app: microservice-template
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: grpc
      port: 8888
      targetPort: 8888
