apiVersion: v1
kind: Service
metadata:
  name: srv-microservice-template
spec:
  selector:
    app: microservice-template
  clusterIP: None
  ports:
    - name: srv-http
      port: 8080
      targetPort: 8080
    - name: srv-grpc
      port: 8888
      targetPort: 8888
