// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/types/error.proto

package types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Error struct {
	Code                 int32                       `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string                      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details              *any.Any                    `protobuf:"bytes,4,opt,name=details,proto3" json:"details,omitempty"`
	Validation           map[string]*ValidationError `protobuf:"bytes,5,rep,name=validation,proto3" json:"validation,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4effa5032fb1515, []int{0}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Error) GetDetails() *any.Any {
	if m != nil {
		return m.Details
	}
	return nil
}

func (m *Error) GetValidation() map[string]*ValidationError {
	if m != nil {
		return m.Validation
	}
	return nil
}

type ValidationError struct {
	Errors               []string `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidationError) Reset()         { *m = ValidationError{} }
func (m *ValidationError) String() string { return proto.CompactTextString(m) }
func (*ValidationError) ProtoMessage()    {}
func (*ValidationError) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4effa5032fb1515, []int{1}
}

func (m *ValidationError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidationError.Unmarshal(m, b)
}
func (m *ValidationError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidationError.Marshal(b, m, deterministic)
}
func (m *ValidationError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidationError.Merge(m, src)
}
func (m *ValidationError) XXX_Size() int {
	return xxx_messageInfo_ValidationError.Size(m)
}
func (m *ValidationError) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidationError.DiscardUnknown(m)
}

var xxx_messageInfo_ValidationError proto.InternalMessageInfo

func (m *ValidationError) GetErrors() []string {
	if m != nil {
		return m.Errors
	}
	return nil
}

func init() {
	proto.RegisterType((*Error)(nil), "types.Error")
	proto.RegisterMapType((map[string]*ValidationError)(nil), "types.Error.ValidationEntry")
	proto.RegisterType((*ValidationError)(nil), "types.ValidationError")
}

func init() { proto.RegisterFile("proto/types/error.proto", fileDescriptor_c4effa5032fb1515) }

var fileDescriptor_c4effa5032fb1515 = []byte{
	// 292 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x51, 0x41, 0x4b, 0xc3, 0x30,
	0x18, 0x25, 0xdb, 0xba, 0xb1, 0xec, 0xa0, 0x04, 0x99, 0x71, 0x78, 0x28, 0x3b, 0x55, 0xd0, 0x04,
	0xea, 0x65, 0x0c, 0x2f, 0x0a, 0xfb, 0x03, 0x01, 0x3d, 0x78, 0x4b, 0xdb, 0x58, 0x83, 0x4d, 0x53,
	0x92, 0xb4, 0x90, 0xbf, 0xee, 0x49, 0x9a, 0xb6, 0x32, 0xbd, 0xe5, 0xbd, 0xef, 0x7d, 0xdf, 0x7b,
	0xbc, 0xc0, 0xeb, 0xc6, 0x68, 0xa7, 0xa9, 0xf3, 0x8d, 0xb0, 0x54, 0x18, 0xa3, 0x0d, 0x09, 0x0c,
	0x8a, 0x02, 0xb5, 0xbb, 0x29, 0xb5, 0x2e, 0x2b, 0x41, 0x03, 0x99, 0xb5, 0x1f, 0x94, 0xd7, 0x7e,
	0x50, 0xec, 0xbf, 0x01, 0x8c, 0x4e, 0xfd, 0x06, 0x42, 0x70, 0x91, 0xeb, 0x42, 0x60, 0x10, 0x83,
	0x24, 0x62, 0xe1, 0x8d, 0x30, 0x5c, 0x29, 0x61, 0x2d, 0x2f, 0x05, 0x9e, 0xc5, 0x20, 0x59, 0xb3,
	0x09, 0x22, 0x02, 0x57, 0x85, 0x70, 0x5c, 0x56, 0x16, 0x2f, 0x62, 0x90, 0x6c, 0xd2, 0x2b, 0x32,
	0x98, 0x90, 0xc9, 0x84, 0x3c, 0xd7, 0x9e, 0x4d, 0x22, 0xf4, 0x04, 0x61, 0xc7, 0x2b, 0x59, 0x70,
	0x27, 0x75, 0x8d, 0xa3, 0x78, 0x9e, 0x6c, 0xd2, 0x5b, 0x12, 0xe2, 0x91, 0xe0, 0x4f, 0xde, 0x7e,
	0xc7, 0xa7, 0xda, 0x19, 0xcf, 0xce, 0xf4, 0xbb, 0x57, 0x78, 0xf1, 0x6f, 0x8c, 0x2e, 0xe1, 0xfc,
	0x4b, 0xf8, 0x90, 0x76, 0xcd, 0xfa, 0x27, 0xba, 0x87, 0x51, 0xc7, 0xab, 0x76, 0x88, 0xba, 0x49,
	0xb7, 0xe3, 0xf5, 0xb3, 0xc5, 0xde, 0x87, 0x0d, 0xa2, 0xe3, 0xec, 0x00, 0xf6, 0x77, 0x7f, 0xce,
	0x86, 0x16, 0xb6, 0x70, 0x19, 0x0a, 0xb4, 0x18, 0xc4, 0xf3, 0x64, 0xcd, 0x46, 0xf4, 0x72, 0x7c,
	0x3f, 0x94, 0xd2, 0x7d, 0xb6, 0x19, 0xc9, 0xb5, 0xa2, 0x85, 0x92, 0xce, 0x78, 0xa5, 0x95, 0x76,
	0x54, 0xc9, 0xdc, 0x68, 0x2b, 0x4c, 0x27, 0x73, 0xf1, 0xe0, 0x84, 0x6a, 0x2a, 0xee, 0xc6, 0xaa,
	0x87, 0x1f, 0xc9, 0x96, 0x01, 0x3c, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0xcd, 0xef, 0xed, 0x4a,
	0xa7, 0x01, 0x00, 0x00,
}
